### ISSUE TITLE
Interface: New full name fields

### ISSUE THREAD

**Issue by MattiasSealander** [humlab/sead_clearinghouse#10]
In some review functions there have been a change of the name fields. Separate first/last name fields have been concatenated to one "full name" field. This hasn't been done for the interface, which is why it must be updated to reflect this change. 
This goes for the following functions/sections:
**Dataset level, "Contacts"** (fn_clearinghouse_review_dataset_contacts_client_data), 
**Dataset level, "Submission"** (fn_clearinghouse_review_dataset_submissions_client_data)

**Comment by MattiasSealander** [comment]
The second function, for submission, also has an error in the SQL which needs to be corrected. The "full name" field is still called "last name" in the LDB section of the SQL.

**Comment by roger-mahler** [comment]
Unable to reproduce problem, both procedures currently returns a single "full_name" field.

**Comment by MattiasSealander** [comment]
**fn_clearinghouse_review_dataset_submissions_client_data**
Part of SQL retrieved from function in staging_clearinghouse, LDB full name field is entered as "last_name". Public data is concatenated and entered as "full_name"

Select

			LDB.local_db_id				               					As local_db_id,
			format('%s %s', LDB.first_name, LDB.last_name)				**As last_name,**
			LDB.submission_type									As submission_type,
			LDB.notes											As notes,
			to_char(LDB.date_submitted,'YYYY-MM-DD')					As date_submitted,

**Comment by MattiasSealander** [comment]
From interface
![bild](https://user-images.githubusercontent.com/44999648/59177567-c3d0bd80-8b5c-11e9-9523-5ce6346ef675.png)
