### ISSUE TITLE
Interface: Dendro dates

### ISSUE THREAD

**Issue by MattiasSealander** [humlab/sead_clearinghouse#7]
Add section for dendro dates on a sample level.
SQL for new function, (99 - new_review_dendo_dates_client_data.sql), returns data in a relevant format and should be rolled out.

**Comment by MattiasSealander** [comment]
While viewing the dendro dates collected on a sample group level is good for research purposes, for reviewing the data in CH it should suffice to keep it at sample level. For building investigations the sample locations are at displayed at a sample level, and for the archaeological data the features dated will (should) be displayed with the dates.

**Comment by roger-mahler** [comment]
Two additional reports installed:
- Sample positions (no data)
- Dendro date notes
